{% set version = "0.17.0" %}

package:
  name: packageurl-python
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/packageurl-python/packageurl_python-{{ version }}.tar.gz
  sha256: 3cc44a01c9549c237f14c34981bae1008eb57c858c0af9039f4f13091807e1f3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}

test:
  imports:
    - packageurl
    - packageurl.contrib
  commands:
    - pip check
    - mypy -p packageurl --ignore-missing-imports
  requires:
    - pip
    - mypy
    - python {{ python_min }}

about:
  home: https://github.com/package-url/packageurl-python
  summary: A purl aka. Package URL parser and builder
  license: MIT
  license_file: mit.LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
