{% set version = "0.13.4" %}

package:
  name: packageurl-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packageurl-python/packageurl-python-{{ version }}.tar.gz
  sha256: 6eb5e995009cc73387095e0b507ab65df51357d25ddc5fce3d3545ad6dcbbee8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - packageurl
    - packageurl.contrib
  commands:
    - pip check
    - mypy -p packageurl --ignore-missing-imports
  requires:
    - pip
    - mypy

about:
  home: https://github.com/package-url/packageurl-python
  summary: A purl aka. Package URL parser and builder
  license: MIT
  license_file: mit.LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
