{% set version = "0.16.0" %}

package:
  name: packageurl-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packageurl-python/packageurl_python-{{ version }}.tar.gz
  sha256: 69e3bf8a3932fe9c2400f56aaeb9f86911ecee2f9398dbe1b58ec34340be365d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - wheel
  run:
    - python >=3.8

test:
  imports:
    - packageurl
    - packageurl.contrib
  commands:
    - pip check
    - mypy -p packageurl --ignore-missing-imports
  requires:
    - pip
    - mypy

about:
  home: https://github.com/package-url/packageurl-python
  summary: A purl aka. Package URL parser and builder
  license: MIT
  license_file: mit.LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
