{% set version = "0.10.1" %}

package:
  name: packageurl-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packageurl-python/packageurl-python-{{ version }}.tar.gz
  sha256: f3a552ac743116cd79e25cfbb8ca8f938b06f91ca2a52deba80f06a2a7010749

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - packageurl
    - packageurl.contrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/package-url/packageurl-python
  summary: A purl aka. Package URL parser and builder
  license: MIT
  license_file: mit.LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
