{% set version = "0.15.6" %}

package:
  name: packageurl-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packageurl-python/packageurl_python-{{ version }}.tar.gz
  sha256: cbc89afd15d5f4d05db4f1b61297e5b97a43f61f28799f6d282aff467ed2ee96

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - packageurl
    - packageurl.contrib
  commands:
    - pip check
    - mypy -p packageurl --ignore-missing-imports
  requires:
    - pip
    - mypy

about:
  home: https://github.com/package-url/packageurl-python
  summary: A purl aka. Package URL parser and builder
  license: MIT
  license_file: mit.LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
