{% set version = "0.14.0" %}

package:
  name: packageurl-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packageurl-python/packageurl-python-{{ version }}.tar.gz
  sha256: ff09147cddaae9e5c59ffcb12df8ec0e1b774b45099399f28c36b1a3dfdf52e2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - packageurl
    - packageurl.contrib
  commands:
    - pip check
    - mypy -p packageurl --ignore-missing-imports
  requires:
    - pip
    - mypy

about:
  home: https://github.com/package-url/packageurl-python
  summary: A purl aka. Package URL parser and builder
  license: MIT
  license_file: mit.LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
