{% set version = "0.9.9" %}

package:
  name: packageurl-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/packageurl-python/packageurl-python-{{ version }}.tar.gz
  sha256: 872a0434b9a448b3fa97571711f69dd2a3fb72345ad66c90b17d827afea82f09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - packageurl
    - packageurl.contrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/package-url/packageurl-python
  summary: A purl aka. Package URL parser and builder
  license: MIT
  license_file: mit.LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
