# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.17.0

package:
  name: packageurl-python
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/packageurl-python/packageurl_python-${{ version }}.tar.gz
  sha256: 3cc44a01c9549c237f14c34981bae1008eb57c858c0af9039f4f13091807e1f3

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - packageurl
        - packageurl.contrib
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - requirements:
      run:
        - mypy
        - python ${{ python_min }}.*
    script:
      - mypy -p packageurl --ignore-missing-imports

about:
  summary: A purl aka. Package URL parser and builder
  license: MIT
  license_file: mit.LICENSE
  homepage: https://github.com/package-url/packageurl-python

extra:
  recipe-maintainers:
    - bollwyvl
